### PR TITLE
Better deployment description

### PR DESCRIPTION
**Pull request by khaosdoctor**
Add a better definition for the deployment description, including how to fill in the fields in the deployment.

### CODE REVIEW

**Comment by khaosdoctor** [comment]
@scotty-c Can you please take a look 😃

**Comment by scotty-c** [comment]
LGTM

**Comment by khaosdoctor** [comment]
I cannot merge it from here, do you know who I should talk to?

**Comment by scotty-c** [comment]
@FBoucher can we get this merged, please? Thanks In adavance

**Pull request merged**
